dataset: 'cbf'
dataset_type: 'TS'
window_size: 5
post_processing: 'min'
pattern_name: ''
rho: '0.100'
network_type: 'ResNet'
appendix_name: ''
parameters:
  batch_size: 32
  scaler_dim: [0, 1]
  preprocessing: True
  reload_images: False