dataset: 'gunpoint'
dataset_type: 'DTW'
rho: '0.001'
window_size: 15
pattern_name: ''
network_type: 'ResNet'
appendix_name: null
parameters:
  batch_size: 32
  scaler_dim: [0, 1]
  preprocessing: True
  reload_images: False