dataset: 'gunpoint'
dataset_type: 'TS'
window_size: 5
pattern_name: ''
rho: None
network_type: 'RNN'
appendix_name: null
parameters:
  batch_size: 32
  scaler_dim: [0, 1]
  preprocessing: True
  reload_images: False